# -*- coding: utf-8 -*-
"""12/16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18TbVopv_s2nnzjaZ4MKCHZ_H0Tl2vzqI
"""

while True:
    acc = input('請輸入帳號?')
    pwd = input('請輸入密碼?')
    if (acc == 'abc' and pwd == '123'):
        print('帳號與密碼正確')
        break
    else:
        print('登入失敗')

password = "a123456"
times = 0

while times <= 3:
    answer = input("Enter Your Password: ") 
    if answer == password: 
        print("登入成功")
        break 
    else:
        times = times + 1
        chance = 3 - times
print("密碼錯誤!還有", chance, "次機會")

sum = 0

for x in range(1, 11, 2):
    sum = sum + x
    
print("1+3+5+7+9=", sum)

n = int(input('請輸入n值?'))
sum = 0;
for i in range(1,n+1):
    sum = sum + i*i;
print(sum)